### ISSUE TITLE
Backspace/Del bug in normal mode

### ISSUE THREAD

**Issue by dysquard** [catweazle9/emacs-everywhere#1]
This script is great!
But I found when I switch to normal mode from emacs mode, in VS2017 or notepad, the Backspace and Delete keys went crazy!
They don't back/forward delete any characters, instead, when you press backspace or delete key, there will be really a string "Backspace" or "Delete"(without quotation marks) on your text filed or input method.
This bug doesn't happen in any other applications outside the default app list.

**Comment by catweazle9** [comment]
Thanks for the bug report. Never noticed it as I don't switch out of Emacs mode!

Should be fixed now - please try again with the latest version in master.
